[project]
name = "student-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.4",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.2",
    "httpx>=0.27.0",
]
